# -*- coding: utf-8 -*-
"""DLR_Mamografia_V2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pKJB9yCMxTcKCcROeD08uGiQfLu4Ekzo
"""

################################################################################
# INSTALL CONDA ON GOOGLE COLAB
################################################################################
! wget https://repo.anaconda.com/miniconda/Miniconda3-py37_4.8.2-Linux-x86_64.sh
! chmod +x Miniconda3-py37_4.8.2-Linux-x86_64.sh
! bash ./Miniconda3-py37_4.8.2-Linux-x86_64.sh -b -f -p /usr/local
import sys
sys.path.append('/usr/local/lib/python3.7/site-packages/')

!conda install -c conda-forge pydicom
!conda install -c conda-forge gdcm

!pip3 install --upgrade gspread

from google.colab import drive
drive.mount("/content/drive")

from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)

#from google.colab import auth
#auth.authenticate_user()

#import gspread
#from oauth2client.client import GoogleCredentials

import pydicom as dicom
import pandas as pd
import numpy as np
import collections
import os
import time

def DLR_Mamografia(r):
  TimeIn=time.time()
  direc=r
  count=0

  isfile = os.path.isfile
  join = os.path.join
  number_of_files = sum(1 for item in os.listdir(direc) if isfile(join(direc, item)))

  print(number_of_files)

  names=[]
  ages=[]
  kvp=[]
  Exp=[]
  thick=[]
  a_f=[]
  proy=[]
  dose=[]
  Ese=[]
  Sede=[]

  #gc = gspread.authorize(GoogleCredentials.get_application_default())
  sh = gc.create('Resultados_DLR_Mamografia')

  worksheet = gc.open('Resultados_DLR_Mamografia').sheet1


  for p in os.listdir(direc):
    #print(os.path.basename(p))
    #print("Imagen %d" %count)  ##Localizar errores archivos que no se puedan leer porque no cumplen las caraterísticas de recolección de datos DICOM
    #count+=1                   ##Imprime el número de imagen leída y así se puede buscar en una lista.
    inf=dicom.dcmread(r+p)
    name=(inf.PatientName)
    age=inf.PatientAge
    kVp=inf.KVP
    mAs=inf.Exposure
    man="MEDELLÍN" if inf.Manufacturer=="GE MEDICAL SYSTEMS" else "RIONEGRO"

    view=str(inf.ImageLaterality)+str(inf.ViewPosition) if man=="MEDELLÍN" else str(inf.ViewPosition)
    thickness=float(inf.BodyPartThickness/10)
    anode_filter=str(inf.AnodeTargetMaterial)+"/"+str(inf.FilterMaterial)
    organDose=float(inf.OrganDose*100)
    entranceDose=inf.EntranceDoseInmGy

    thick.append(thickness)
    a_f.append(anode_filter)
    dose.append(organDose)
    Ese.append(entranceDose)
    proy.append(view)
    names.append(name)
    ages.append(age)
    Sede.append(man)
    kvp.append(kVp)
    Exp.append(mAs)

  information={"Edad":ages,"Compresión [cm]":thick,"Ánodo-Filtro":a_f,"Dosis en órgano[mGy]":dose,"Dosis de Entrada[mGy]":Ese,"Proyección":proy,"kVp":kvp,"mAs":Exp,"Sede":Sede}
  df=pd.DataFrame(information,columns=["Edad","Compresión [cm]","Ánodo-Filtro","Dosis en órgano[mGy]","Dosis de Entrada[mGy]","Proyección","kVp","mAs","Sede"])

  worksheet.update([df.columns.values.tolist()] + df.values.tolist())

  while True:

    T1=np.array(["LCC","RCC","LMLO","RMLO"])
    print("\n","Copie y pegue una opción de las siguientes en el cuadro de ingreso:","\n","\n",T1,"\n")

    est=input("Ingrese proyección a evaluar:")

    if est in T1:

      df1=df[df["Proyección"]==est]
      wks=sh.add_worksheet(title=est,rows=1000,cols=100)
      wks.update([df1.columns.values.tolist()] + df1.values.tolist())
      print("\n",df1,"\n")
      print("\n","Nivel de Referencia en mama proyección:",est,":",df1["Dosis en órgano[mGy]"].median(),"mGy","\n","Dosis promedio en mama proyección",est,":",df1["Dosis en órgano[mGy]"].mean(),"mGy","\n")
      print("\n","Compresión Referencia en mama proyección:",est,":",df1["Compresión [cm]"].median(),"cm","\n","Compresión promedio en mama proyección",est,":",df1["Compresión [cm]"].mean(),"mGy","\n")
      print("\n","Kv de nivel de referencia en:",est,":",df1["kVp"].median(),"kV","\n","mAs de nivel de referencia en",est,":",df1["mAs"].median(),"mAs","\n","Kv promedio en:",est,":",df1["kVp"].mean(),"kV","\n","mAs promedio en",est,":",df1["mAs"].mean(),"mAs","\n")

    elif est not in T1:
      print("\n","Estudio inválido","\n")
      break

  timeOut=time.time()

  print ("El proceso tardó:",timeOut - TimeIn,"Segundos","\n")

DLR_Mamografia("/content/drive/MyDrive/ACTIVIDADES/Labores/NivelesDeReferencia/DLR/Mamografía/")